name: anilist

on:
  workflow_dispatch:
  schedule:
    # Once a week "At 00:00 on Sunday" (see https://crontab.guru/once-a-week)
    - cron: "0 0 * * 0"

jobs:
  update-pool:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # 3-hours
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}
          repository: ker0olos/fable
      
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno run -A --unstable packs/anilist/pool.ts
    
      - uses: actions/upload-artifact@v3
        with:
          name: anilist-pool
          path: packs/anilist/pool.json
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: 'Updated "anilist/pool.json"'
          commit-message: '[bot] Updated "anilist/pool.json"'
          branch: update-anilist-pool
          delete-branch: true
          body: |
            This PR is auto-generated

            Updated the pool cache for each possible gacha query

            (See #9 #45)
          labels: |
            anilist
