name: deno

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_review:
    types: [submitted]
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno fmt --config deno.json --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno lint --config deno.json

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno test --unstable --config deno.json -A --coverage=cov_profile
      - run: deno coverage cov_profile --lcov --output=lcov.info
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs:
      - test
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: denoland/deployctl@v1
        with:
          project: ${{ secrets.DENO_ID }}
          entrypoint: src/interactions.ts
