name: discord

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_review:
    types: [submitted]
    branches: [main]

jobs:
  update-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - if: github.ref != 'refs/heads/main'
        name: Set environment to dummy
        run: echo "GUILD_ID=${{ secrets.DUMMY_GUILD }}" >> "$GITHUB_ENV"

      - name: Update Commands
        run: deno run -A update_commands.ts
        env:
          APP_ID: ${{ secrets.APP_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
